# Generated by Django 3.1.7 on 2021-02-25 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_user_head'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
    ]
