# Generated by Django 3.1.7 on 2021-02-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_auto_20210225_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
