# Generated by Django 3.1.7 on 2021-02-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_auto_20210225_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='form_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='hotel_rent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='meal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='others',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='transport',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
