# Generated by Django 3.1.7 on 2021-02-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_auto_20210225_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='dufault', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='dufault', max_length=100),
        ),
    ]
