# Generated by Django 3.1.7 on 2021-02-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_auto_20210225_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='form_status',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
