# Generated by Django 3.1.7 on 2021-02-27 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0011_auto_20210227_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.department'),
        ),
    ]
