# Generated by Django 3.1.7 on 2021-02-27 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0012_expenses_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='department_head',
        ),
    ]
