# Generated by Django 3.1.7 on 2021-02-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0014_auto_20210227_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='airfare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenses',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenses',
            name='travel_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
